const CONFIG = {
    TARGET_FPS: 60,
    FRAME_TIME: 1000 / 60,
    GRID_CELL_SIZE: 100,
    TARGET_SPAWN_INTERVAL: 2000,
    TARGET_MAX_LIFESPAN: 8000,
    TARGET_FADE_START_PERCENT: 0.75,
    PROJECTILE_SPEED: 5,
    PROJECTILE_RADIUS: 5,
    INITIAL_POOL_SIZE: 20,
    TARGET_MIN_SIZE: 10,
    TARGET_SIZE_VARIATION: 20,
    COLORS: {
        PLAYER: 'blue',
        TARGET: 'green',
        PROJECTILE: 'red'
    }
};
